# $FreeBSD$

PORTNAME=	digikam
PORTVERSION=	${DIGIKAM_VER}
PORTREVISION=	2
CATEGORIES=	graphics kde
PKGNAMESUFFIX=	-kde4-doc

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Documentation for digiKam, showFoto, and Kipi-plugins

CONFLICTS_INSTALL=	digikam-2.* kipi-plugins-2.*

WRKSRC=		${WRKDIR}/${DISTNAME}/doc

.include "${.CURDIR}/../digikam-kde4/Makefile.common"
.include <bsd.port.mk>
