--- pyproject.toml.orig	2025-01-24 10:33:32 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [project]
-name = "vfbLib"
+name = "vfblib"
 dynamic = ["version"]
 description = "Tools for converting FontLab Studio 5 (VFB) files."
 keywords = ["vfb", "vfbLib", "fonttools"]
