# $FreeBSD: branches/plasma5/KDE/devel/kf5-kunitconversion/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	kunitconversion
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 library for unit conversion

USES=		cmake:outsource compiler:c++11-lib gettext kde:5 pkgconfig tar:xz
USE_KDE=	ecm i18n
USE_QT5=	buildtools_build core network qmake_build xml

.include <bsd.port.mk>
