# $FreeBSD: branches/plasma5/KDE/misc/libkeduvocdocument-kf5/Makefile 13702 2017-03-08 18:02:29Z tcberner $

PORTNAME=	libkeduvocdocument
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	misc kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Library for reading and writing vocabulary files

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	archive ecm i18n kio
USE_QT5=	buildtools_build core gui qmake_build xml

.include <bsd.port.mk>
