Obtained from:	https://github.com/python-openapi/openapi-schema-validator/commit/1f93f5be800625f3ef9350acaff111c3f441c598

--- pyproject.toml.orig	2023-10-05 11:16:22 UTC
+++ pyproject.toml
@@ -57,7 +57,7 @@ rfc3339-validator = "*" # requred by jsonschema for da
 python = "^3.8.0"
 jsonschema = "^4.19.1"
 rfc3339-validator = "*" # requred by jsonschema for date-time checker
-jsonschema-specifications = "^2023.5.2"
+jsonschema-specifications = ">=2023.5.2"
 
 [tool.poetry.extras]
 docs = ["sphinx", "sphinx-immaterial"]
