# Created by: Rusty Nejdl <rnejdl@ringofsaturn.com>
# $FreeBSD: head/sysutils/filelight-kde4/Makefile 439367 2017-04-25 08:20:30Z riggs $

PORTNAME=	filelight
PORTVERSION=	${KDE4_VERSION}
PORTREVISION=	1
CATEGORIES=	sysutils kde kde-kde4

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Map of concentric segmented-rings representing file system

USES=		cmake:outsource kde:4 tar:xz
USE_KDE=	kdelibs automoc4
USE_QT4=	qmake_build moc_build rcc_build uic_build

.include <bsd.port.mk>
