--- lapce-proxy/Cargo.toml.orig	2024-05-08 07:36:00 UTC
+++ lapce-proxy/Cargo.toml
@@ -51,7 +51,7 @@ libc          = "0.2"
 libc          = "0.2"
 
 # git
-git2 = { version = "0.18.2", features = ["vendored-openssl"] }
+git2 = { version = "0.18.2" }
 
 # deleting files
 trash = "3.0.6"
