--- Cargo.toml.orig	2024-04-24 20:32:06 UTC
+++ Cargo.toml
@@ -61,6 +61,10 @@ url               = { version = "2.5.0" }
 toml              = { version = "*" }
 toml_edit         = { version = "0.20.2", features = ["serde"] }
 url               = { version = "2.5.0" }
+tracing           = { git = "https://github.com/tokio-rs/tracing", rev = "908cc432a5994f6e17c8f36e13c217dc40085704", package = "tracing" }
+tracing-log       = { git = "https://github.com/tokio-rs/tracing", rev = "908cc432a5994f6e17c8f36e13c217dc40085704", package = "tracing-log" }
+tracing-subscriber = { git = "https://github.com/tokio-rs/tracing", rev = "908cc432a5994f6e17c8f36e13c217dc40085704", package = "tracing-subscriber" }
+tracing-appender = { git = "https://github.com/tokio-rs/tracing", rev = "908cc432a5994f6e17c8f36e13c217dc40085704", package = "tracing-appender" }
 
 lsp-types = { version = "0.95.1", features = ["proposed"] }                                                  # not following semver, so should be locked to patch version updates only
 psp-types = { git = "https://github.com/lapce/psp-types", rev = "f7fea28f59e7b2d6faa1034a21679ad49b3524ad" }
@@ -75,30 +79,8 @@ floem-editor-core = { git = "https://github.com/lapce/
 # floem-editor-core = { path = "../workspaces/floem/editor-core/", features = ["serde"] }
 
 [patch.crates-io]
-# Temporarily patch lsp-types with a version that supports inline-completion
-lsp-types = { git = "https://github.com/lapce/lsp-types", rev = "feaa1e2ec80975c9dadd400a238ceacf071058e6" }
-regalloc2 = { rev = "5d79e12d0a93b10fc181f4da409b4671dd365228", git = "https://github.com/bytecodealliance/regalloc2" }
-
-
-[workspace.dependencies.tracing]
-git     = "https://github.com/tokio-rs/tracing"
-rev     = "908cc432a5994f6e17c8f36e13c217dc40085704"
-package = "tracing"
-
-[workspace.dependencies.tracing-log]
-git     = "https://github.com/tokio-rs/tracing"
-rev     = "908cc432a5994f6e17c8f36e13c217dc40085704"
-package = "tracing-log"
-
-[workspace.dependencies.tracing-subscriber]
-git     = "https://github.com/tokio-rs/tracing"
-rev     = "908cc432a5994f6e17c8f36e13c217dc40085704"
-package = "tracing-subscriber"
-
-[workspace.dependencies.tracing-appender]
-git     = "https://github.com/tokio-rs/tracing"
-rev     = "908cc432a5994f6e17c8f36e13c217dc40085704"
-package = "tracing-appender"
+lsp-types = { path = '../lsp-types-feaa1e2ec80975c9dadd400a238ceacf071058e6' }
+regalloc2 = { path = '../regalloc2-5d79e12d0a93b10fc181f4da409b4671dd365228' }
 
 [workspace.dependencies.alacritty_terminal]
 version = "0.23.0"
