--- pyproject.toml.orig	2024-03-02 12:09:14 UTC
+++ pyproject.toml
@@ -30,7 +30,7 @@ dependencies = [
     "Topic :: Software Development :: Build Tools",
 ]
 dependencies = [
-    "httpx==0.27.*",
+    "httpx>=0.27",
 ]
 dynamic = ["version"]
 
@@ -63,4 +63,4 @@ filterwarnings = [
 [tool.pytest.ini_options]
 filterwarnings = [
     "error",
-]
\ No newline at end of file
+]
