# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD$

PORTNAME=	kdewebdev
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	www kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Tools for html/website development environment

USES=		kde:4 metaport

RUN_DEPENDS=	kfilereplace:sysutils/kfilereplace \
		kimagemapeditor:graphics/kimagemapeditor \
		klinkstatus:www/klinkstatus

.include <bsd.port.mk>
