--- pyproject.toml.orig	2025-04-21 14:51:57.000000000 -0700
+++ pyproject.toml	2025-04-21 21:08:26.075285000 -0700
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 66.1.0, <= 76.0.0", "wheel == 0.45.1"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
+requires = ["setuptools >= 63.1.0, <= 76.0.0", "wheel == 0.45.1"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
 build-backend = "setuptools.build_meta"
 
 [project]
