--- pyproject.toml.orig	2025-03-25 11:10:19.000000000 -0700
+++ pyproject.toml	2025-04-09 10:51:48.677552000 -0700
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 66.1.0, <= 76.0.0"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
+requires = ["setuptools >= 63.1.0, <= 76.0.0"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
 build-backend = "setuptools.build_meta"
 
 [project]
