--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["hatchling>=1.11", "jupyterlab>=4.2.0,<4.3"]
+requires = ["hatchling>=1.11", "jupyterlab>=4.2.0,<4.4"]
 build-backend = "hatchling.build"
 
 [project]
@@ -32,7 +32,7 @@ dependencies = [
 ]
 dependencies = [
     "jupyter_server>=2.4.0,<3",
-    "jupyterlab>=4.2.0,<4.3",
+    "jupyterlab>=4.2.0,<4.4",
     "jupyterlab_server>=2.27.1,<3",
     "notebook_shim>=0.2,<0.3",
     "tornado>=6.2.0",
