--- pyproject.toml.orig	2023-03-26 11:49:21 UTC
+++ pyproject.toml
@@ -40,7 +40,7 @@ python = "^3.7"
 
 [tool.poetry.dependencies]
 python = "^3.7"
-isodate = "^0.6.0"
+isodate = ">=0.6.0"
 pyparsing = ">=2.1.0,<4"
 importlib-metadata = {version = "^4.0.0", python = ">=3.7,<3.8"}
 berkeleydb = {version = "^18.1.0", optional = true}
