# $FreeBSD$

PORTNAME=	kdesdk-thumbnailers
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	devel kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE thumbnail generator for gettext po files

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	config ecm i18n kio
USE_QT5=	buildtools_build core gui qmake_build widgets

.include <bsd.port.mk>
