# $FreeBSD: branches/plasma5/KDE/devel/cervisia/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	cervisia
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	devel kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	CVS Frontend for KDE

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	dbusaddons doctools ecm iconthemes init itemviews kdesu \
		notifications parts widgetsaddons
USE_QT5=	buildtools_build core dbus gui qmake_build widgets

.include <bsd.port.mk>
