#!/bin/sh
#
# $FreeBSD: head/editors/openoffice-devel/files/openoffice-wrapper 397932 2015-09-26 07:40:47Z truckman $

program=`echo $0 | sed -e 's|.*%%EXECBASE%%-||'`

case $program in
$0)
	exec %%OOPATH%%/program/soffice "$@"
	;;
printeradmin)
	exec %%OOPATH%%/program/spadmin
	;;
*)
	exec %%OOPATH%%/program/$program "$@"
	;;
esac
