# $FreeBSD: branches/plasma5/KDE/devel/asynqt/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	asynqt
PORTVERSION=	5.18.0
CATEGORIES=	devel kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Framework providing convenience methods which make QFuture actually useful

USES=		cmake:outsource gettext kde:5 pathfix
USE_KDE=	config coreaddons ecm i18n kio service
USE_QT5=	core \
		buildtools_build qmake_build

USE_GITHUB=	yes
GH_ACCOUNT=	KDE
GH_TAGNAME=	feb30f9

.include <bsd.port.mk>
