# $FreeBSD: branches/plasma5/KDE/x11-wm/plasma5-kdecoration/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	kdecoration
PORTVERSION=	${KDE_PLASMA_VERSION}
CATEGORIES=	x11-wm kde kde-plasma

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Plasma5 library to create window decorations

USES=		cmake:outsource compiler:c++11-lib cpe kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core gui qmake_build testlib

.include <bsd.port.mk>
