# $FreeBSD: branches/plasma5/KDE/textproc/kf5-kcodecs/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	kcodecs
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
PORTREVISION=	1
CATEGORIES=	textproc kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 library for string manipulation

USES=		cmake:outsource compiler:c++11-lib gperf kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core linguisttools qmake_build

.include <bsd.port.mk>
