# $FreeBSD$
#

    COMMENT = Ukrainian support

    SUBDIR += aspell
    SUBDIR += emacs-koi8u
    SUBDIR += gd
    SUBDIR += hunspell
    SUBDIR += hyphen
    SUBDIR += kde-l10n
    SUBDIR += libreoffice
    SUBDIR += monacofonts
    SUBDIR += mythes
    SUBDIR += webalizer

.include <bsd.port.subdir.mk>
