# $FreeBSD: branches/plasma5/KDE/net/kf5-kxmlrpcclient/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	kxmlrpcclient
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	net kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 interaction with XMLRPC services

USES=		cmake:outsource compiler:c++11-lib gettext kde:5 tar:xz
USE_KDE=	config coreaddons ecm doctools i18n kio service
USE_QT5=	buildtools_build core gui qmake_build xml

.include <bsd.port.mk>
