# Created by: tcberner
# $FreeBSD: branches/plasma5/KDE/misc/kdeedu-data-kf5/Makefile 13702 2017-03-08 18:02:29Z tcberner $

PORTNAME=	kdeedu-data
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	misc kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE edu data files

USES=		cmake:outsource kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build qmake_build

.include <bsd.port.mk>
