--- kak-lsp.toml.orig	2019-05-11 23:33:08 UTC
+++ kak-lsp.toml
@@ -54,11 +54,22 @@ roots = ["requirements.txt", "setup.py", ".git", ".hg"
 command = "pyls"
 offset_encoding = "utf-8"
 
+#[language.c_cpp]
+#filetypes = ["c", "cpp"]
+#roots = ["compile_commands.json", ".cquery"]
+#command = "cquery"
+#args = ["--init={\"cacheDirectory\":\"/tmp/cquery\",\"highlight\":{\"enabled\":true}}"]
+
 [language.c_cpp]
 filetypes = ["c", "cpp"]
-roots = ["compile_commands.json", ".cquery"]
-command = "cquery"
-args = ["--init={\"cacheDirectory\":\"/tmp/cquery\",\"highlight\":{\"enabled\":true}}"]
+roots = ["compile_commands.json", ".ccls", ".git"]
+command = "ccls"
+# With completion.detailedLabel turned on ccls embeds type
+# signatures and other metadata in completion entries.  Kak-lsp
+# does not filter them, so they appear alongside the selected entry,
+# which is not very convenient.  It is recommended that you disable
+# it.
+args = ["--init={\"completion\":{\"detailedLabel\":false}}"]
 
 [language.haskell]
 filetypes = ["haskell"]
