--- pyproject.toml.orig	1970-01-01 00:00:00 UTC
+++ pyproject.toml
@@ -14,7 +14,7 @@ dependencies = [
     # which requires some adaptions to our code.
     "importlib-metadata (>=4.4,<8.7) ; python_version < '3.10'",
     "installer (>=0.7.0,<0.8.0)",
-    "keyring (>=25.1.0,<26.0.0)",
+    "keyring (>=23.9.0,<26.0.0)",
     # packaging uses calver, so version is unclamped
     "packaging (>=24.0)",
     "pkginfo (>=1.12,<2.0)",
