--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -3,7 +3,7 @@ build-backend = "hatchling.build"
 
 [build-system]
 build-backend = "hatchling.build"
-requires = ["hatchling>=1.4.0", "hatch-nodejs-version", "jupyterlab>=4.0.0"]
+requires = ["hatchling>=1.4.0", "hatch-nodejs-version"]
 
 [project]
 name = "jupyter_collaboration"
@@ -30,7 +30,7 @@ dependencies = [
     "jupyter_server>=2.0.0,<3.0.0",
     "jupyter_ydoc>=2.0.0,<3.0.0",
     "pycrdt",
-    "pycrdt-websocket>=0.14.0,<0.15.0",
+    "pycrdt-websocket>=0.14.0,<0.16.0",
     "jupyter_events>=0.10.0",
     "jupyter_server_fileid>=0.7.0,<1",
     "jsonschema>=4.18.0"
