# $FreeBSD$

PORTNAME=	svgpart
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	graphics kde kde-applications
PKGNAMEPREFIX=	kdegraphics-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	SVG KPart

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	coreaddons ecm parts
USE_QT5=	buildtools_build core qmake_build svg widgets

.include <bsd.port.mk>
