# $FreeBSD: branches/plasma5/KDE/devel/kf5-kitemmodels/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	kitemmodels
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
PORTREVISION=	1
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 models for Qt Model/View system

USES=		cmake:outsource compiler:c++11-lib kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core qmake_build testlib_build

.include <bsd.port.mk>
