--- pyproject.toml.orig	2024-10-07 13:29:58 UTC
+++ pyproject.toml
@@ -40,21 +40,20 @@ pylint = ">=3.0"
 [tool.poetry.dependencies]
 python = ">=3.8.1,<4.0"
 pylint = ">=3.0"
-pylint-celery = "0.3"
 pylint-django = "~2.5"
-pylint-plugin-utils = "~0.7"
+pylint-plugin-utils = ">=0.7"
 pylint-flask = "0.6"
 requirements-detector = ">=1.2.0"
 PyYAML = "*"
 mccabe = "^0.7.0"
-flake8 = "<7.0.0"
+flake8 = "<8.0.0"
 pyflakes = ">=2.2.0,<4.*"
 pycodestyle = ">=2.9.0"
-pep8-naming = ">=0.3.3,<=0.10.0"
+pep8-naming = ">=0.3.3"
 pydocstyle = ">=2.0.0"
 dodgy = "^0.2.1"
 toml = "^0.10.2"
-setoptconf-tmp = "^0.3.1"
+setoptconf = "^0.3.0"
 GitPython = "^3.1.27"
 packaging = "*"
 bandit = {version = ">=1.5.1", optional = true}
