--- Cargo.toml.orig	2024-12-11 16:41:25 UTC
+++ Cargo.toml
@@ -140,7 +140,6 @@ git = ["git2"]
 [features]
 default = ["git"]
 git = ["git2"]
-vendored-openssl = ["git2/vendored-openssl"]
 vendored-libgit2 = ["git2/vendored-libgit2"]
 # Should only be used inside of flake.nix
 nix = []
