# $FreeBSD: branches/plasma5/KDE/devel/kf5-kconfig/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	kconfig
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 widgets for configuration dialogs

USES=		cmake:outsource compiler:c++11-lib kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build concurrent core gui linguisttools \
		qmake_build testlib xml

.include <bsd.port.mk>
