# $FreeBSD$

PORTNAME=	kdegraphics-thumbnailers
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	graphics kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Thumbnailers for various graphics file formats

USES=		cmake:outsource kde:5 tar:xz
USE_KDE=	ecm libkdcraw libkexiv2 kio
USE_QT5=	buildtools_build core gui qmake_build

.include <bsd.port.mk>
