# $FreeBSD$

PORTNAME=	kde-l10n
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	chinese kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Simplified Chinese messages and documentation for KDE

KDE_L10N=	zh_CN

.include "${.CURDIR:H:H}/misc/kde-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
