--- pyproject.toml.orig	2024-10-07 09:04:30 UTC
+++ pyproject.toml
@@ -1,9 +1,9 @@
 [build-system]
-requires = ["setuptools~=65.6", "wheel~=0.37.1"]
+requires = ["setuptools>=61", "wheel>=0.37.1"]
 build-backend = "setuptools.build_meta"
 
 [project]
-name         = "PyChromecast"
+name         = "pychromecast"
 version      = "14.0.4"
 description  = "Python module to talk to Google Chromecast."
 readme       = "README.rst"
