# $FreeBSD: branches/plasma5/KDE/lang/kturtle/Makefile 13829 2017-04-09 08:51:06Z tcberner $

PORTNAME=	kturtle
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	lang kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Educational programming environment for KDE

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	ecm emoticons i18n init itemmodels \
		kdelibs4support kio newstuff
USE_QT5=	buildtools_build core gui qmake_build svg widgets xml

.include <bsd.port.mk>
