--- pyproject.toml.orig	2024-04-17 09:50:53 UTC
+++ pyproject.toml
@@ -19,12 +19,12 @@ dependencies = [
 
 dependencies = [
     "python >=3.8",
-    "orjson ~= 3.5.1",
+    "orjson ~= 3.5, >=3.5.1",
     "fonttools >=4.40.0",
     "ufoLib2 >=0.11.1",
     "openstep-plist >=0.2.2",
     "glyphsLib >=5.3.2",
-    "fontfeatures ~= 1.0.6",
+    "fontfeatures ~= 1.0, >=1.0.6",
 ]
 
 [project.optional-dependencies]
