# $FreeBSD: branches/plasma5/KDE/games/blinken/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	blinken
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	games kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Memory enhancement game for KDE

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	dbusaddons doctools ecm guiaddons i18n xmlgui
USE_QT5=	buildtools_build core gui phonon4 qmake_build svg widgets

.include <bsd.port.mk>
