# $FreeBSD: branches/plasma5/KDE/devel/kf5-kpackage/Makefile 13591 2017-01-14 18:07:11Z tcberner $

PORTNAME=	kpackage
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
PORTREVISION=	1
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 library to load and install packages

USES=		cmake:outsource compiler:c++11-lib gettext kde:5 tar:xz
USE_KDE=	archive config coreaddons doctools ecm i18n
USE_QT5=	buildtools_build core qmake_build xml

.include <bsd.port.mk>
