--- pyproject.toml.orig	2024-09-18 22:07:19 UTC
+++ pyproject.toml
@@ -1,7 +1,7 @@ requires = [
 [build-system]
 requires = [
-  "setuptools ~= 75.1",
-  "wheel ~= 0.44",
+  "setuptools",
+  "wheel",
   "pyTooling ~= 6.5"
 ]
 build-backend = "setuptools.build_meta"
