Disable using V8 custom libcxx.

--- Cargo.toml.orig
+++ Cargo.toml
@@ -51,7 +51,7 @@ repository = "https://github.com/denoland/deno"
 
 [workspace.dependencies]
 deno_ast = { version = "=0.46.2", features = ["transpiling"] }
-deno_core = { version = "0.341.0" }
+deno_core = { version = "0.341.0", default-features = false, features = ["include_icu_data"] }
 
 deno_bench_util = { version = "0.190.0", path = "./bench_util" }
 deno_config = { version = "=0.51.0", features = ["workspace"] }
