--- cargo-crates/ring-0.16.15/Cargo.toml.orig	2020-06-17 01:27:06 UTC
+++ cargo-crates/ring-0.16.15/Cargo.toml
@@ -70,7 +70,7 @@ version = "1.3.1"
 features = ["std"]
 optional = true
 default-features = false
-[target."cfg(any(target_os = \"android\", target_os = \"linux\"))".dependencies.libc]
+[target."cfg(any(target_os = \"android\", target_os = \"linux\", target_os = \"freebsd\"))".dependencies.libc]
 version = "0.2.69"
 default-features = false
 [target."cfg(any(unix, windows))".dev-dependencies.libc]
