Disable using V8 custom libcxx.

--- Cargo.toml.orig
+++ Cargo.toml
@@ -51,7 +51,7 @@ deno_ast = { version = "=0.46.2", features = ["transpi
 
 [workspace.dependencies]
 deno_ast = { version = "=0.46.2", features = ["transpiling"] }
-deno_core = { version = "0.342.0" }
+deno_core = { version = "0.342.0", default-features = false, features = ["include_icu_data"] }
 
 deno_bench_util = { version = "0.193.0", path = "./bench_util" }
 deno_config = { version = "=0.52.0", features = ["workspace"] }
