--- pyproject.toml.orig	2025-02-20 08:07:54 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=68.2.0"]
+requires = ["setuptools>=61"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -32,7 +32,7 @@ dependencies = [
 dependencies = [
     "aiohttp >= 3.9.2, < 4.0.0",
     "aioitertools >= 0.5.1, < 1.0.0",
-    "botocore >= 1.36.20, < 1.36.24", # NOTE: When updating, always keep `project.optional-dependencies` aligned
+    "botocore >= 1.36.20", # NOTE: When updating, always keep `project.optional-dependencies` aligned
     "python-dateutil >= 2.1, < 3.0.0",
     "jmespath >= 0.7.1, < 2.0.0",
     "multidict >= 6.0.0, < 7.0.0",
@@ -43,10 +43,10 @@ awscli = [
 
 [project.optional-dependencies]
 awscli = [
-    "awscli >= 1.37.20, < 1.37.24",
+    "awscli >= 1.29.81",
 ]
 boto3 = [
-    "boto3 >= 1.36.20, < 1.36.24",
+    "boto3 >= 1.36.20",
 ]
 
 [project.urls]
