--- pyproject.toml.orig	2024-10-09 13:09:02 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=68.2.0"]
+requires = ["setuptools>=61"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -30,7 +30,7 @@ dependencies = [
 dynamic = ["version", "readme"]
 
 dependencies = [
-    "botocore >=1.35.16, <1.35.37", # NOTE: When updating, always keep `project.optional-dependencies` aligned
+    "botocore >=1.35.16", # NOTE: When updating, always keep `project.optional-dependencies` aligned
     "aiohttp >=3.9.2, <4.0.0",
     "wrapt >=1.10.10, <2.0.0",
     "aioitertools >=0.5.1, <1.0.0",
@@ -38,10 +38,10 @@ awscli = [
 
 [project.optional-dependencies]
 awscli = [
-    "awscli >=1.34.16, <1.35.3",
+    "awscli >=1.29.81",
 ]
 boto3 = [
-    "boto3 >=1.35.16, <1.35.37",
+    "boto3 >=1.35.16",
 ]
 
 [project.urls]
