# $FreeBSD: branches/plasma5/KDE/textproc/libkomparediff2/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	libkomparediff2
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	textproc kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Library to compare files and strings

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	codecs config coreaddons ecm i18n kio parts xmlgui
USE_QT5=	buildtools_build core qmake_build widgets
USE_LDCONFIG=	yes

.include <bsd.port.mk>
