Avoid dependencies on libgit2, libssh2, etc.

--- Cargo.toml.orig	2019-03-20 19:25:57 UTC
+++ Cargo.toml
@@ -58,12 +58,6 @@ version = "1"
 optional = true
 version = "0.8"
 
-[dev-dependencies]
-lazy_static = "1"
-regex = "1.0"
-tempfile = "3.0.7"
-git2 = "0.8.0"
-
 [features]
 all = ["json", "cbor", "yaml"]
 cbor = ["hex", "serde_cbor"]
