# $FreeBSD$

PORTNAME=	libkipi
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	graphics kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE Image Plugin Interface

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	config ecm i18n libkdcraw libkexiv2 service xmlgui
USE_QT5=	buildtools_build core gui qmake_build widgets
USE_LDCONFIG=	yes

.include <bsd.port.mk>
