# $FreeBSD: branches/plasma5/KDE/devel/kasync/Makefile 13970 2017-04-26 19:42:11Z tcberner $

PORTNAME=	kasync
DISTVERSION=	0.1.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	C++ library for controlling asynchronous tasks

USES=		cmake:outsource kde:5
USE_KDE=	ecm
USE_QT5=	core testlib \
		buildtools_build qmake_build

USE_GITHUB=	yes
GH_ACCOUNT=	KDE

.include <bsd.port.mk>
