--- pyproject.toml.orig	2024-06-29 09:11:31.605531000 -0700
+++ pyproject.toml	2024-06-29 09:11:56.996337000 -0700
@@ -102,7 +102,6 @@
 
 
 [tool.pytest.ini_options]
-addopts = "-v -Wdefault --cov=zeroconf --cov-report=term-missing:skip-covered"
 pythonpath = ["src"]
 
 [tool.coverage.run]
