# $FreeBSD$

PORTNAME=	kdenetwork-filesharing
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	net kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE Filesharing via Samba

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	coreaddons doctools ecm i18n kio widgetsaddons
USE_QT5=	buildtools_build core gui qmake_build widgets

.include <bsd.port.mk>
