# $FreeBSD: branches/plasma5/KDE/devel/poxml/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	poxml
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	devel kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Tools to translate Docbook XML using gettext

USES=		cmake:outsource gettext-tools:build,run kde:5 tar:xz
USE_KDE=	doctools ecm
USE_QT5=	buildtools_build core qmake_build xml

.include <bsd.port.mk>
