--- pyproject.toml.orig	2025-04-01 16:12:26 UTC
+++ pyproject.toml
@@ -1,7 +1,7 @@ version = "0.1.11"
 [project]
 name = "proglog"
 version = "0.1.11"
-license = "MIT"
+license = { text = "MIT" }
 authors = [{ name = "Zulko" }]
 description = "Log and progress bar manager for console, notebooks, web..."
 readme = "pypi-readme.rst"
