--- pueue_lib/Cargo.toml.orig	2024-05-13 20:16:13 UTC
+++ pueue_lib/Cargo.toml
@@ -64,9 +64,4 @@ winapi = { version = "0.3", features = [
 
 # Unix
 [target.'cfg(unix)'.dependencies]
-libproc = "0.14.2"
 whoami = "1"
-
-# Linux only
-[target.'cfg(target_os = "linux")'.dependencies]
-procfs = { version = "0.16", default-features = false }
