--- pyproject.toml.orig	1970-01-01 00:00:00 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["maturin>=1.8.3,<2.0"]
+requires = ["maturin>=1.8.2,<2.0"]
 build-backend = "maturin"
 
 [project]
