# $FreeBSD: branches/plasma5/KDE/x11-themes/kf5-kemoticons/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	kemoticons
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	x11-themes kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 library to convert emoticons

USES=		cmake:outsource compiler:c++11-lib kde:5 tar:xz
USE_KDE=	archive config coreaddons ecm service
USE_QT5=	buildtools_build core gui qmake_build widgets xml

.include <bsd.port.mk>
