# $FreeBSD: branches/plasma5/KDE/security/plasma5-ksshaskpass/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	ksshaskpass
PORTVERSION=	${KDE_PLASMA_VERSION}
CATEGORIES=	security kde kde-plasma

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Plasma5 ssh-add frontend

USES=		cmake:outsource compiler:c++11-lib cpe gettext kde:5 tar:xz
USE_KDE=	coreaddons doctools ecm i18n wallet widgetsaddons
USE_QT5=	buildtools_build core gui qmake_build widgets

.include <bsd.port.mk>
