# $FreeBSD$

PORTNAME=	kde-l10n
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	french kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	French messages and documentation for KDE

KDE_L10N=	fr

.include "${.CURDIR:H:H}/misc/kde-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
