# $FreeBSD: branches/plasma5/KDE/x11-clocks/kteatime/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	kteatime
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	x11-clocks kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Handy timer for steeping tea

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	config crash doctools ecm i18n iconthemes notifications \
		notifyconfig textwidgets widgetsaddons xmlgui
USE_QT5=	buildtools_build core dbus gui qmake_build widgets

.include <bsd.port.mk>
