# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: branches/plasma5/KDE/sysutils/kdf/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	kdf
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	sysutils kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Shows free space of devices for KDE

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	configwidgets coreaddons doctools i18n iconthemes kcmutils kio \
		notifications widgetsaddons xmlgui
USE_QT5=	buildtools_build qmake_build

.include <bsd.port.mk>
