# $FreeBSD: branches/plasma5/KDE/deskutils/kruler/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	kruler
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	deskutils kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE screen ruler

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	ecm doctools i18n notifications windowsystem xmlgui
USE_QT5=	buildtools_build core gui qmake_build x11extras widgets
USE_XORG=	x11

.include <bsd.port.mk>
