--- pyproject.toml.orig	2026-04-05 21:42:40 UTC
+++ pyproject.toml
@@ -9,7 +9,7 @@ requires = [
     "packaging",
     # XXX dependence on wheel is historical, with setuptools >= v70.1.0 this is not needed anymore
     "wheel !=0.38.0, !=0.38.1",
-    "ctypesgen @ git+https://github.com/pypdfium2-team/ctypesgen@8ab382671a113cb7b9123e1d5ae5a554d4cb52e6",
+    # ctypesgen (pypdfium2 fork) is not required when PDFIUM_BINDINGS=reference
 ]
 
 [tool.cibuildwheel]
