# $FreeBSD: branches/plasma5/KDE/graphics/kolourpaint/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	kolourpaint
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	graphics kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE 4 paint program

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	ecm emoticons init itemmodels kdelibs4support libkexiv2 libksane
USE_QT5=	buildtools_build core gui qmake_build widgets
USE_LDCONFIG=	yes

.include <bsd.port.mk>
