# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/PORTS/x11/libfakekey/Makefile 11849 2016-01-22 06:52:09Z rakuco $

PORTNAME=	libfakekey
DISTVERSION=	0.1
CATEGORIES=	x11 kde
MASTER_SITES=	http://downloads.yoctoproject.org/releases/matchbox/${PORTNAME}/${PORTVERSION}/

MAINTAINER=	kde@FreeBSD.org
COMMENT=	X virtual keyboard library

LICENSE=	LGPL20+

USES=		libtool pathfix pkgconfig
USE_XORG=	x11 xtst
GNU_CONFIGURE=	YES
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
