--- pyproject.toml.orig	2025-04-03 12:23:45 UTC
+++ pyproject.toml
@@ -1,7 +1,7 @@ requires = [
 [build-system]
 requires = [
     "setuptools",
-    "cython>=3.0,<4.0",
+    "cython>=0,<4.0",
     "numpy>=1.19.3,<3.0.0"
 ]
 build-backend = "setuptools.build_meta"
