# $FreeBSD: branches/plasma5/KDE/math/kmplot/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	kmplot
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	math kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Mathematical function plotter for KDE

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	ecm guiaddons emoticons i18n init itemmodels kdelibs4support \
		parts widgetsaddons
USE_QT5=	buildtools_build core gui printsupport qmake_build svg widgets

.include <bsd.port.mk>
