--- pyproject.toml.orig	2024-12-16 12:18:54 UTC
+++ pyproject.toml
@@ -6,7 +6,7 @@ requires = [
     "cymem>=2.0.2,<2.1.0",
     "preshed>=3.0.2,<3.1.0",
     "blis>=1.1.0,<1.2.0",
-    "numpy>=2.0.0,<3.0.0",
+    "numpy>=1.19.0,<3.0.0",
 ]
 build-backend = "setuptools.build_meta"
 
