# $FreeBSD: branches/plasma5/KDE/archivers/kf5-karchive/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	karchive
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	archivers kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 library that provides classes for handling archive formats

USES=		cmake:outsource compiler:c++11-lib kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core qmake_build

.include <bsd.port.mk>
