# Created by: miwi
# $FreeBSD: branches/plasma5/PORTS/devel/automoc4/Makefile 13566 2017-01-06 22:31:30Z tcberner $

PORTNAME=	automoc4
DISTVERSION=	0.9.88
PORTREVISION=	6
CATEGORIES=	devel kde
MASTER_SITES=	KDE/stable/${PORTNAME}/${PORTVERSION}/
DIST_SUBDIR=	KDE

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Automatic moc for Qt 4 packages

USE_QT4=	corelib moc qmake_build rcc_build uic_build
USES=		cmake tar:bzip2

.include <bsd.port.mk>
