# $FreeBSD: branches/plasma5/KDE/x11-themes/plasma5-breeze-gtk/Makefile 13957 2017-04-26 14:25:40Z tcberner $

PORTNAME=	breeze-gtk
DISTVERSION=	${KDE_PLASMA_VERSION}
CATEGORIES=	x11-themes kde kde-plasma

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Plasma5 Breeze visual style for Gtk

USES=		cmake:outsource cpe kde:5 pkgconfig tar:xz
USE_GNOME=	gdkpixbuf2
USE_KDE=	ecm
USE_QT5=	buildtools_build core qmake_build

.include <bsd.port.mk>
