# $FreeBSD: branches/plasma5/KDE/devel/kf5-kpty/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	kpty
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
PORTREVISION=	1
CATEGORIES=	devel kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 pty abstraction

USES=		cmake:outsource compiler:c++11-lib gettext kde:5 tar:xz
USE_KDE=	coreaddons ecm i18n
USE_QT5=	buildtools_build core qmake_build

.include <bsd.port.mk>
