# Created by: Marie Loise Nolden <nolden@kde.org>
# $FreeBSD$

PORTNAME=	qt5-style-plugins
DISTVERSION=	5.0.0
PORTREVISION=	1
CATEGORIES=	x11-themes
MASTER_SITES=	QT/community_releases/additional_qt_src_pkgs/
DISTNAME=	qtstyleplugins-src-${PORTVERSION}
DIST_SUBDIR=	KDE/Qt/addons

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Additional Styles for Qt 5 and KDE

LICENSE=	LGPL21

USES=		qmake:outsource
USE_QT5=	buildtools_build core gui widgets
USE_GL+=	gl

.include <bsd.port.mk>
