--- pyproject.toml.orig	2025-05-04 11:11:07 UTC
+++ pyproject.toml
@@ -10,10 +10,7 @@ readme = "README.md"
 name = 'pydot'
 description = "Python interface to Graphviz's Dot"
 readme = "README.md"
-license = "MIT"
-license-files = [
-   'LICENSES/*',
-]
+license = {text = "MIT"}
 requires-python = ">= 3.8"
 dependencies = [
   'pyparsing>=3.0.9'
