# $FreeBSD: branches/plasma5/KDE/misc/kgeography/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	kgeography
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	misc kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE geography trainer

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	configwidgets coreaddons doctools ecm i18n iconthemes \
		itemviews service widgetsaddons xmlgui
USE_QT5=	buildtools_build gui qmake_build widgets xml

.include <bsd.port.mk>
