# Created by: tcberner
# $FreeBSD: branches/plasma5/KDE/x11-themes/plasma5-plasma-workspace-wallpapers/Makefile 13409 2016-11-22 11:08:09Z tcberner $

PORTNAME=	plasma-workspace-wallpapers
PORTVERSION=	${KDE_PLASMA_VERSION}
CATEGORIES=	x11-themes kde kde-plasma

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Plasma5 wallpapers

USES=		cmake:outsource cpe kde:5 tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build qmake_build

.include <bsd.port.mk>
