--- pyproject.toml.orig	2024-12-31 06:42:16 UTC
+++ pyproject.toml
@@ -17,7 +17,7 @@ python = ">=3.8.1,<4.0, !=3.9.7"
 
 [tool.poetry.dependencies]
 python = ">=3.8.1,<4.0, !=3.9.7"
-httpx = ">=0.23.0,<0.28.0"
+httpx = ">=0.23.0,<1.0.0"
 openai = ">=1.55.3"
 python-dotenv = ">=0.2.0"
 tiktoken = ">=0.7.0"
