--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -41,7 +41,7 @@ dependencies = [
 # install requirements depending on python version
 # see https://www.python.org/dev/peps/pep-0508/#environment-markers
 dependencies = [
-    'icalendar >= 6.1.0, < 7.0.0',
+    'icalendar >= 4.0.0, < 7.0.0',
     'python-dateutil >= 2.8.1, < 3.0.0',
     'x-wr-timezone >= 1.0.0, < 3.0.0; python_version >= "3.9"',
     'x-wr-timezone == 0.*; python_version <= "3.8"',
