# $FreeBSD: branches/plasma5/KDE/x11-toolkits/kf5-attica/Makefile 13250 2016-11-06 16:34:10Z tcberner $

PORTNAME=	attica
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	x11-toolkits kde kde-frameworks

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Open Collaboration Services API library KDE5 version

USES=		cmake:outsource compiler:c++11-lib kde:5 pathfix tar:xz
USE_KDE=	ecm
USE_QT5=	buildtools_build core gui network qmake_build testlib_build widgets

.include <bsd.port.mk>
