# $FreeBSD: branches/plasma5/KDE/misc/klettres/Makefile 13724 2017-03-10 19:28:23Z tcberner $

PORTNAME=	klettres
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	misc kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Alphabet learning tool for KDE

USES=		cmake:outsource gettext kde:5 tar:xz
USE_KDE=	completion configwidgets coreaddons \
		doctools ecm emoticons i18n init \
		itemmodels kdelibs4support newstuff \
		widgetsaddons
USE_QT5=	buildtools_build core gui qmake_build svg

.include <bsd.port.mk>
