# $FreeBSD$

PORTNAME=	kde-l10n
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	korean kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Korean messages and documentation for KDE

KDE_L10N=	ko

.include "${.CURDIR:H:H}/misc/kde-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
