--- Cargo.toml.orig	2025-09-19 01:31:02 UTC
+++ Cargo.toml
@@ -93,11 +93,11 @@ reqwest = { version = "0.11", features = ["json", "rus
 reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
 
 # llama.cpp bindings (optional) - using forked version with macOS ARM64 i8mm fix
-llama-cpp-2 = { version = "0.1.118", optional = true, default-features = false }
+#llama-cpp-2 = { version = "0.1.118", optional = true, default-features = false }
 
 # Use forked llama-cpp-2 with macOS ARM64 i8mm compatibility fix
-[patch.crates-io]
-llama-cpp-2 = { git = "https://github.com/Michael-A-Kuykendall/llama-cpp-rs.git", branch = "fix-macos-arm64-i8mm", package = "llama-cpp-2" }
+#[patch.crates-io]
+llama-cpp-2 = { git = "https://github.com/Michael-A-Kuykendall/llama-cpp-rs.git", branch = "fix-macos-arm64-i8mm", package = "llama-cpp-2", optional = true, default-features = false }
 
 [dev-dependencies]
 tokio-tungstenite = "0.20"
